### ISSUE TITLE
可以封装一个jar包

### ISSUE THREAD

**Issue by c472672231** [ZShUn/spring-data-jpa-expansion#1]
可以把你这个类封装一个jar包，然后提供到中央仓库，留个群号，如果更新了，发个全体通知

**Comment by c472672231** [comment]
而且最好不要用lombok

**Comment by ZShUn** [comment]
首先感谢你的建议,这周我会完成jar丢到中央仓库,同时发布两个版本含lombok和不含lombok.

**Comment by c472672231** [comment]
还有就是spring怎么整合这个东西麻烦也写上， 因为我这看这个是springboot的整合……

**Comment by ZShUn** [comment]
群号849555205.spring方式后续都会完善.
